# Generated by Django 4.1.2 on 2022-10-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200, verbose_name='Darbo pavadinimas')),
                ('pastabos', models.TextField(blank=True, max_length=2000, verbose_name='Pastabos')),
            ],
            options={
                'verbose_name': 'Darbas',
                'verbose_name_plural': '4 - Darbai',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(help_text='Įveskite darbuotojo vardą', max_length=100, verbose_name='Vardas')),
                ('pavarde', models.CharField(help_text='Įveskite darbuotojo pavardę', max_length=100, verbose_name='Pavardė')),
                ('imone', models.CharField(help_text='Įveskite darbuotojo įmonę', max_length=100, verbose_name='Įmonė')),
            ],
            options={
                'verbose_name': 'Darbuotojas',
                'verbose_name_plural': '3 - Darbuotojai',
            },
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('imone', models.CharField(max_length=100, verbose_name='Įmonė')),
                ('kontaktai', models.CharField(help_text='Įveskite telefoną', max_length=200, verbose_name='Kontaktai')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': '2 - Klientai',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Projekto pavadinimas', max_length=200, verbose_name='Pavadinimas')),
                ('pradzia', models.DateTimeField(help_text='Įveskite projekto pradžios datą', max_length=200, verbose_name='Pradžios data')),
                ('pabaiga', models.DateTimeField(help_text='Įveskite projekto pabaigos datą', max_length=200, verbose_name='Pabaigos data')),
                ('klientas', models.CharField(help_text='Įveskite projekto užsakovą', max_length=200, verbose_name='Klientas')),
                ('darbai', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.darbas')),
                ('darbuotojai', models.ManyToManyField(help_text='Įveskite darbuotojo vardą ir pavardę', max_length=200, to='project.darbuotojas')),
            ],
            options={
                'verbose_name': 'Projektas',
                'verbose_name_plural': '1 - Projektai',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pradzia', models.DateTimeField(help_text='Įveskite sąskaitos išrašymo datą', verbose_name='Išrašymo data')),
                ('suma', models.IntegerField(verbose_name='Suma')),
                ('pavadinimas', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projektas')),
            ],
            options={
                'verbose_name': 'Sąskaita',
                'verbose_name_plural': '5 - Sąskaitos',
            },
        ),
        migrations.AddField(
            model_name='projektas',
            name='saskaitos',
            field=models.ForeignKey(blank=True, help_text='Įveskite sąskaitos numerį', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.saskaita'),
        ),
        migrations.AddField(
            model_name='projektas',
            name='vadovas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
