# Generated by Django 4.1.2 on 2022-10-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_darbuotojas_imone'),
    ]

    operations = [
        migrations.AddField(
            model_name='darbas',
            name='atsakingas_darbuotojas',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.darbuotojas'),
        ),
        migrations.AlterField(
            model_name='darbas',
            name='pavadinimas',
            field=models.CharField(help_text='Įveskite darbo pavadinimą', max_length=200, verbose_name='Pavadinimas'),
        ),
    ]
