# Generated by Django 4.1.2 on 2022-10-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_projektas_pavadinimas'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='nuotrauka',
            field=models.ImageField(default='default.png', null=True, upload_to='covers'),
        ),
    ]
