# Generated by Django 4.1.2 on 2022-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projektas_nuotrauka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektas',
            name='nuotrauka',
            field=models.ImageField(default='default.png', null=True, upload_to='covers', verbose_name='Nuotrauka'),
        ),
    ]
