# Generated by Django 4.1.2 on 2022-10-25 04:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_projektas_nuotrauka'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='aprasymas',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True, verbose_name='Aprašymas'),
        ),
    ]
